-- Enable PostGIS for geospatial queries (Critical for "Search by Map")
create extension if not exists postgis;

-- ============================================
-- 1. LOCATIONS (Hierarchical)
-- ============================================
-- Example: Punta del Este (City) -> La Barra (Zone) -> Montoya (Neighborhood)
create table public.locations (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  type text check (type in ('city', 'zone', 'neighborhood', 'beach')),
  parent_id bigint references public.locations(id),
  coordinates geography(point), -- Center point
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ============================================
-- 2. AGENCIES (Inmobiliarias)
-- ============================================
create table public.agencies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text not null unique,
  logo_url text,
  description text,
  tier_subscription text default 'basic' check (tier_subscription in ('basic', 'pro', 'enterprise')),
  contact_email text,
  contact_phone text,
  whatsapp text,
  website text,
  address text,
  city text,
  is_verified boolean default false,
  -- Metrics (denormalized for performance)
  total_properties int default 0,
  total_views int default 0
);

-- ============================================
-- 3. PROFILES (Extends auth.users)
-- ============================================
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role text default 'agent' check (role in ('admin', 'agent', 'user')),
  avatar_url text,
  phone text,
  whatsapp text,
  bio text,
  license_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ============================================
-- 4. AGENCY_USERS (Junction Table)
-- ============================================
-- Links users to agencies with roles
create table public.agency_users (
  id bigint generated by default as identity primary key,
  agency_id bigint references public.agencies(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(agency_id, user_id)
);

-- Index for fast lookups
create index agency_users_user_id_idx on public.agency_users(user_id);
create index agency_users_agency_id_idx on public.agency_users(agency_id);

-- ============================================
-- 5. PROPERTIES
-- ============================================
create table public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Fields
  title text not null,
  slug text not null unique, -- SEO Friendly URL
  description text,
  price numeric not null,
  currency text default 'USD' check (currency in ('USD', 'UYU')),
  status text default 'for_sale' check (status in ('for_sale', 'for_rent', 'sold', 'rented')),
  is_featured boolean default false, -- For "Destacar" functionality
  
  -- Dimensions & Specs
  built_area numeric, -- m2
  plot_area numeric, -- m2
  bedrooms int,
  bathrooms int,
  garage_spaces int,
  
  -- Taxonomies
  location_id bigint references public.locations(id) not null,
  agency_id bigint references public.agencies(id), -- NEW: Links to agency
  agent_id uuid references public.profiles(id), -- Assigned agent within agency
  
  -- Rich Media & Features
  main_image text,
  images text[], -- Array of image URLs
  video_url text,
  floor_plan_url text,
  
  -- "Lifestyle Matching" Engine
  -- JSONB allows us to add specific features without schema migration (e.g. {"has_pool": true, "view_type": "ocean"})
  features jsonb default '{}'::jsonb, 
  
  -- Tags for "Surf & Olas", "Forest & Silence" logic
  lifestyle_tags text[], 
  
  -- Geospatial
  location_point geography(point),
  
  -- Metrics
  view_count int default 0
);

-- ============================================
-- 6. INDEXES for Performance
-- ============================================
create index properties_location_id_idx on public.properties(location_id);
create index properties_agency_id_idx on public.properties(agency_id);
create index properties_lifestyle_tags_idx on public.properties using gin(lifestyle_tags);
create index properties_features_idx on public.properties using gin(features);
create index properties_geo_idx on public.properties using gist(location_point);
create index properties_is_featured_idx on public.properties(is_featured) where is_featured = true;

-- ============================================
-- 7. RLS POLICIES
-- ============================================

-- === AGENCIES RLS ===
alter table public.agencies enable row level security;

-- Everyone can view agencies
create policy "Agencies are viewable by everyone"
  on public.agencies for select using (true);

-- Only agency owners/admins can update their agency
create policy "Agency owners can update their agency"
  on public.agencies for update
  using (
    exists (
      select 1 from public.agency_users
      where agency_users.agency_id = agencies.id
        and agency_users.user_id = auth.uid()
        and agency_users.role in ('owner', 'admin')
    )
  );

-- Anyone authenticated can create an agency (during registration)
create policy "Authenticated users can create agencies"
  on public.agencies for insert
  with check (auth.uid() is not null);

-- === AGENCY_USERS RLS ===
alter table public.agency_users enable row level security;

-- Users can see their own agency memberships
create policy "Users can see their agency memberships"
  on public.agency_users for select
  using (user_id = auth.uid());

-- Agency owners can see all members of their agency
create policy "Agency owners can see all agency members"
  on public.agency_users for select
  using (
    exists (
      select 1 from public.agency_users au
      where au.agency_id = agency_users.agency_id
        and au.user_id = auth.uid()
        and au.role = 'owner'
    )
  );

-- Agency owners can manage members
create policy "Agency owners can manage members"
  on public.agency_users for insert
  with check (
    -- Either creating their own membership (registration)
    user_id = auth.uid()
    or
    -- Or they're an owner adding someone else
    exists (
      select 1 from public.agency_users au
      where au.agency_id = agency_users.agency_id
        and au.user_id = auth.uid()
        and au.role = 'owner'
    )
  );

create policy "Agency owners can remove members"
  on public.agency_users for delete
  using (
    exists (
      select 1 from public.agency_users au
      where au.agency_id = agency_users.agency_id
        and au.user_id = auth.uid()
        and au.role = 'owner'
    )
  );

-- === PROPERTIES RLS ===
alter table public.properties enable row level security;

-- Everyone can view active properties
create policy "Public properties are viewable by everyone" 
  on public.properties for select 
  using (status in ('for_sale', 'for_rent'));

-- Agency members can insert properties for their agency
create policy "Agency members can insert properties"
  on public.properties for insert
  with check (
    exists (
      select 1 from public.agency_users
      where agency_users.agency_id = properties.agency_id
        and agency_users.user_id = auth.uid()
    )
  );

-- Agency members can update their agency's properties
create policy "Agency members can update their agency properties"
  on public.properties for update
  using (
    exists (
      select 1 from public.agency_users
      where agency_users.agency_id = properties.agency_id
        and agency_users.user_id = auth.uid()
    )
  );

-- Only agency owners/admins can delete properties
create policy "Agency admins can delete properties"
  on public.properties for delete
  using (
    exists (
      select 1 from public.agency_users
      where agency_users.agency_id = properties.agency_id
        and agency_users.user_id = auth.uid()
        and agency_users.role in ('owner', 'admin')
    )
  );

-- === PROFILES RLS ===
alter table public.profiles enable row level security;

-- Everyone can view profiles
create policy "Public profiles are viewable by everyone"
  on public.profiles for select using (true);

-- Users can update their own profile
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Users can insert their own profile
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

-- ============================================
-- 8. HELPER FUNCTIONS
-- ============================================

-- Function to get user's agency
create or replace function public.get_user_agency(user_uuid uuid)
returns bigint
language sql
security definer
stable
as $$
  select agency_id from public.agency_users where user_id = user_uuid limit 1;
$$;

-- Function to check if user belongs to agency
create or replace function public.user_belongs_to_agency(user_uuid uuid, agency_id_param bigint)
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from public.agency_users 
    where user_id = user_uuid and agency_id = agency_id_param
  );
$$;

