-- ============================================
-- VIBE SCORES TABLE
-- Geospatial lifestyle data for "Lifestyle Matching" engine
-- ============================================

-- Vibe scores table for storing calculated lifestyle metrics
CREATE TABLE IF NOT EXISTS public.vibe_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Foreign keys (one or the other, not both)
  location_id BIGINT REFERENCES public.locations(id) ON DELETE CASCADE,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  
  -- Coordinates for independent zone scoring
  coordinates GEOGRAPHY(POINT),
  zone_polygon GEOGRAPHY(POLYGON), -- For heat map zones
  
  -- Core Scores (0-100, higher = more intense)
  wind_score INT CHECK (wind_score BETWEEN 0 AND 100) DEFAULT 50,
  noise_score INT CHECK (noise_score BETWEEN 0 AND 100) DEFAULT 50,
  safety_score INT CHECK (safety_score BETWEEN 0 AND 100) DEFAULT 50,
  
  -- Lifestyle Zone Classifications
  surf_zone BOOLEAN DEFAULT FALSE,        -- Good for surfing (high wind, coastal)
  nightlife BOOLEAN DEFAULT FALSE,         -- High activity nightlife area
  total_silence BOOLEAN DEFAULT FALSE,     -- Ultra quiet residential
  forest_retreat BOOLEAN DEFAULT FALSE,    -- Nature/forest area
  beach_access BOOLEAN DEFAULT FALSE,      -- Direct beach access
  
  -- Composite Score (auto-calculated)
  overall_vibe INT GENERATED ALWAYS AS (
    (COALESCE(wind_score, 50) + COALESCE(noise_score, 50) + COALESCE(safety_score, 50)) / 3
  ) STORED,
  
  -- Seasonality
  season TEXT CHECK (season IN ('summer', 'winter', 'transition')) DEFAULT 'summer',
  season_modifier INT DEFAULT 0, -- Offset applied during season change
  
  -- Data Sources & Metadata
  data_sources JSONB DEFAULT '{}'::JSONB,
  last_calculated TIMESTAMPTZ DEFAULT NOW(),
  next_refresh TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days'),
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Constraints
  CONSTRAINT vibe_scores_target_check CHECK (
    (location_id IS NOT NULL AND property_id IS NULL) OR
    (location_id IS NULL AND property_id IS NOT NULL) OR
    (coordinates IS NOT NULL)
  )
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS vibe_scores_location_idx ON public.vibe_scores(location_id);
CREATE INDEX IF NOT EXISTS vibe_scores_property_idx ON public.vibe_scores(property_id);
CREATE INDEX IF NOT EXISTS vibe_scores_season_idx ON public.vibe_scores(season);
CREATE INDEX IF NOT EXISTS vibe_scores_geo_idx ON public.vibe_scores USING GIST(coordinates);
CREATE INDEX IF NOT EXISTS vibe_scores_zone_idx ON public.vibe_scores USING GIST(zone_polygon);
CREATE INDEX IF NOT EXISTS vibe_scores_lifestyle_idx ON public.vibe_scores(surf_zone, nightlife, total_silence);

-- ============================================
-- RLS POLICIES
-- ============================================
ALTER TABLE public.vibe_scores ENABLE ROW LEVEL SECURITY;

-- Everyone can view vibe scores (public data)
CREATE POLICY "Vibe scores are viewable by everyone"
  ON public.vibe_scores FOR SELECT USING (true);

-- Only service role can insert/update vibe scores (automated process)
CREATE POLICY "Only service role can manage vibe scores"
  ON public.vibe_scores FOR ALL
  USING (auth.role() = 'service_role');

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Function to get vibe score for a location
CREATE OR REPLACE FUNCTION public.get_vibe_score(loc_id BIGINT)
RETURNS TABLE (
  wind_score INT,
  noise_score INT,
  safety_score INT,
  overall_vibe INT,
  surf_zone BOOLEAN,
  nightlife BOOLEAN,
  total_silence BOOLEAN
)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT 
    wind_score, noise_score, safety_score, overall_vibe,
    surf_zone, nightlife, total_silence
  FROM public.vibe_scores 
  WHERE location_id = loc_id
  LIMIT 1;
$$;

-- Function to find properties by lifestyle vibe
CREATE OR REPLACE FUNCTION public.find_by_vibe(
  p_surf BOOLEAN DEFAULT NULL,
  p_nightlife BOOLEAN DEFAULT NULL,
  p_silence BOOLEAN DEFAULT NULL,
  p_season TEXT DEFAULT 'summer'
)
RETURNS SETOF public.properties
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT p.*
  FROM public.properties p
  INNER JOIN public.vibe_scores v ON v.property_id = p.id
  WHERE 
    (p_surf IS NULL OR v.surf_zone = p_surf)
    AND (p_nightlife IS NULL OR v.nightlife = p_nightlife)
    AND (p_silence IS NULL OR v.total_silence = p_silence)
    AND v.season = p_season
  ORDER BY v.overall_vibe DESC;
$$;

-- ============================================
-- TRIGGER for updated_at
-- ============================================
CREATE OR REPLACE FUNCTION public.update_vibe_scores_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_vibe_scores_timestamp
  BEFORE UPDATE ON public.vibe_scores
  FOR EACH ROW
  EXECUTE FUNCTION public.update_vibe_scores_timestamp();

-- ============================================
-- SEED INITIAL ZONE DATA (Punta del Este)
-- ============================================
-- @TODO: These will be populated by the data ingestor script
-- Example zones for development:

INSERT INTO public.vibe_scores (coordinates, surf_zone, nightlife, total_silence, wind_score, noise_score, safety_score, season, data_sources)
VALUES 
  -- La Barra (Surf Zone)
  (ST_SetSRID(ST_MakePoint(-54.8711, -34.9126), 4326)::geography, TRUE, TRUE, FALSE, 85, 70, 75, 'summer', '{"source": "manual_seed"}'::jsonb),
  -- José Ignacio (Exclusive/Quiet)
  (ST_SetSRID(ST_MakePoint(-54.6478, -34.8500), 4326)::geography, TRUE, FALSE, TRUE, 70, 20, 95, 'summer', '{"source": "manual_seed"}'::jsonb),
  -- Punta del Este Centro (Nightlife)
  (ST_SetSRID(ST_MakePoint(-54.9500, -34.9700), 4326)::geography, FALSE, TRUE, FALSE, 40, 85, 80, 'summer', '{"source": "manual_seed"}'::jsonb),
  -- Punta Ballena (Forest/Quiet)
  (ST_SetSRID(ST_MakePoint(-55.0200, -34.9100), 4326)::geography, FALSE, FALSE, TRUE, 60, 15, 90, 'summer', '{"source": "manual_seed"}'::jsonb)
ON CONFLICT DO NOTHING;
